
services:
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123458
      POSTGRES_DB: orders
      POSTGRES_USER: postgres

    volumes:
      - ./postgres:/var/lib/postgresql/data